name: Markdown Links

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          check-modified-files-only: "no"
          config-file: ".github/markdown-link-check.json"
